appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OfIfsXLEESbqeO4VwqprnQwa7361EM/ekp5VcbX4ZTrDntxdi7fR0usGNXzg9N1AeYW4a8XOZT00ajEfXggvHkOC2h1tS8NAxKsP5xtpOJeTzYQAEsiiHCV4kOX793xcjW8knCiLvNzALn+HC6u76YLU5hJelOHs4rOwgGYVMAgwk6zS1pca9WD8d8FNp7aaQWIwquf0x35vJbxsm/C8tQqxZFlMC0Z5TQ9NY+du/A9RyF/hwoHmWND5ysfsfA9HyNQEmDrS5ctafQUxPwSL4wgC8kzFDoLY92KKw2ZnNWkmHIIhlvmE7RSETRUjFJgRjJpcJcbxN6HKR+T4v48iz+xE4bMopBOkazRPv+CTEX1oEUPN0Zm5OZ+St38MGUi0YAXgQgm+hLBSfGJcegv+7gPboE8MBVL9euJ+v4bmRyNWPPYPbzFQxxlrgQ7TXMackLgY0w+7r5opz1mlPL32oMswhL2Scbl5YyuvBZq7jBQvmXovw1f6ECkmpHrnP64xLPvqnIg9PT74lMgWWKV7qZL8itQlzh4cnfFlyc3Dmpv8TybKVi66biYedSkNUAiq6/OqV4B01rR+Mn+D4g/g0sN9cuYNWVBLx+nwE2PRKwT51MYvtEowl17TnvM90UQ+swyCGAHi+TznHP6vgz4TZF25tozzRYFL3azmv+THuSo=}
