travis:
  secure:
    BINSTAR_TOKEN: hOJdy1oq9QfYaFPKwZeDEijGyig6XspiC+/oGQ0H9NosNeQqe/GGzJQPB7xNXfljm+0PqnMVVUJwShcWF44kF3G2+Mh5+YIjzhXHbs9FCHR4eHqMpJ2zOHw+sBjLePk2vJE8Lu/AAXp3dLEOeeAzyWqJ1b3gMde8+WWCE+R028MbN3sJ/phex9KhIqqpZt4ETAIiM/AufuFwsAF27V9VqhCbFxAX0GonABhKSLIX90E1+iZTCsyDmYe7z1cGMhElknU9C6w6JDcIFTOkAmamORzKsHFeBL8KlvYjuRrSG5KwvWxD7qQMWTzk+8to5ZNxs2T86fkO2VpxfFWNqKnG635HLMbdC1SRw173p5bidqC5MYTEMvotQLWnCj62MPq/QMJigtQNK/t1mSS5jvCOUHnULcxRgoDuniEzqYTrF+vY93qIPL0P7/sR68LjuMog+PLtndeIIsDOmUxuwU+oRJmjzY6upLdkEPWwyZrJSIWxPIOMQ6fKb2bQF2FsmGPSNuBCfFFuiQZA6z4yLj8AirLVqJhVupYQMkl/FdMeldUfaxAjIikZOuHdBSX4pvaIKRwss4xgweaKj14Dh+02FBcdUIAuxhdB4pC5GXx10OHqEbttVK0m9d5uPgDrDd/pK6fTt9jTnOUg+wJEhHegYnMtHFs8S2kHpjSQ5/UKjWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
